from fastapi import APIRouter, Depends, HTTPException, status, Query, UploadFile, File
from sqlalchemy.orm import Session
from sqlalchemy import or_, func
from typing import Optional
import re
import io
import csv

from app.database import get_db
from app.models.user import User
from app.models.machine import Machine
from app.models.payment import Payment
from app.models.service import Service
from app.dependencies import get_current_user
from app.core.security import get_password_hash
from app.schemas.machine import MachineCreate, MachineUpdate, MachineResponse, MachineStatusUpdate
from app.schemas.common import SuccessResponse, MessageResponse
from app.utils.alert_service import create_alert_if_not_exists, resolve_machine_alerts
from app.models.alert import AlertSeverity

router = APIRouter()


@router.post("/", response_model=SuccessResponse[MachineResponse], status_code=status.HTTP_201_CREATED)
async def create_machine(
    machine_data: MachineCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Create a new machine with auto-generated username.
    
    The username is generated by combining the prefix with an auto-incremented number.
    For example, if prefix is "admin", usernames will be: admin001, admin002, etc.
    
    Args:
        machine_data: Machine creation data
        db: Database session
        current_user: Current authenticated user
        
    Returns:
        Created machine details
    """
    # Generate username with auto-increment
    prefix = machine_data.username_prefix
    
    # Find the highest number with this prefix
    existing_machines = db.query(Machine).filter(
        Machine.username.like(f"{prefix}%")
    ).order_by(Machine.username.desc()).all()
    
    # Extract numbers and find the max
    max_number = 0
    for machine in existing_machines:
        # Extract number from username (e.g., "admin001" -> 1)
        match = re.search(r'(\d+)$', machine.username)
        if match:
            number = int(match.group(1))
            max_number = max(max_number, number)
    
    # Generate new username
    new_number = max_number + 1
    username = f"{prefix}{new_number:03d}"  # e.g., admin001
    
    # Hash password
    hashed_password = get_password_hash(machine_data.password)
    
    # Create machine
    machine = Machine(
        user_id=current_user.id,  # Auto-assign to current admin
        name=machine_data.name,
        location=machine_data.location,
        username=username,
        hashed_password=hashed_password,
        status="offline",
        location_id=machine_data.location_id or None,
    )
    
    try:
        db.add(machine)
        db.commit()
        db.refresh(machine)
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to create machine: {str(e)}"
        )
    
    return {
        "success": True,
        "data": MachineResponse(
            id=str(machine.id),
            user_id=str(machine.user_id),
            name=machine.name,
            location=machine.location,
            username=machine.username,
            status=machine.status,
            upi_id=machine.upi_id,
            location_id=str(machine.location_id) if machine.location_id else None,
            last_sync=machine.last_sync,
            online_collection=float(machine.online_collection),
            offline_collection=float(machine.offline_collection),
            created_at=machine.created_at,
            updated_at=machine.updated_at
        )
    }


@router.get("/", response_model=SuccessResponse[dict])
async def get_machines(
    page: int = Query(1, ge=1, description="Page number"),
    limit: int = Query(20, ge=1, le=100, description="Items per page"),
    status: Optional[str] = Query(None, pattern="^(online|offline|maintenance)$", description="Filter by status"),
    search: Optional[str] = Query(None, description="Search by name, location, or username"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get list of all machines with pagination and filtering.
    
    Query Parameters:
        page: Page number (default: 1)
        limit: Items per page (default: 20, max: 100)
        status: Filter by status (online | offline | maintenance)
        search: Search by name, location, or username
        
    Returns:
        Paginated list of machines
    """
    query = db.query(Machine).filter(Machine.user_id == current_user.id)  # Filter by admin
    
    # Apply filters
    if status:
        query = query.filter(Machine.status == status)
    
    if search:
        search_pattern = f"%{search}%"
        query = query.filter(
            or_(
                Machine.name.ilike(search_pattern),
                Machine.location.ilike(search_pattern),
                Machine.username.ilike(search_pattern)
            )
        )
    
    # Get total count
    total = query.count()
    
    # Apply pagination
    machines = query.order_by(Machine.created_at.desc()).offset((page - 1) * limit).limit(limit).all()
    
    # Calculate stats efficiently
    if machines:
        machine_ids = [m.id for m in machines]
        
        # Calculate online collections per machine
        online_stats = db.query(Payment.machine_id, func.sum(Payment.amount))\
            .filter(
                Payment.machine_id.in_(machine_ids),
                Payment.status == 'success',
                Payment.method.in_(['UPI', 'Card'])
            )\
            .group_by(Payment.machine_id).all()
        online_map = {str(mid): float(amount or 0) for mid, amount in online_stats}

        # Calculate offline collections per machine
        offline_stats = db.query(Payment.machine_id, func.sum(Payment.amount))\
            .filter(
                Payment.machine_id.in_(machine_ids),
                Payment.status == 'success',
                Payment.method.in_(['Cash'])
            )\
            .group_by(Payment.machine_id).all()
        offline_map = {str(mid): float(amount or 0) for mid, amount in offline_stats}
    else:
        online_map = {}
        offline_map = {}
    
    # Convert to response format
    machines_data = [
        MachineResponse(
            id=str(m.id),
            user_id=str(m.user_id),
            name=m.name,
            location=m.location,
            username=m.username,
            status=m.status,
            upi_id=m.upi_id,
            location_id=str(m.location_id) if m.location_id else None,
            last_sync=m.last_sync,
            online_collection=online_map.get(str(m.id), 0.0),
            offline_collection=offline_map.get(str(m.id), 0.0),
            created_at=m.created_at,
            updated_at=m.updated_at
        )
        for m in machines
    ]
    
    return {
        "success": True,
        "data": {
            "machines": machines_data,
            "pagination": {
                "current_page": page,
                "total_pages": (total + limit - 1) // limit,
                "total_items": total,
                "items_per_page": limit
            }
        }
    }


@router.get("/{machine_id}", response_model=SuccessResponse[MachineResponse])
async def get_machine(
    machine_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get detailed information about a specific machine.
    
    Args:
        machine_id: Machine UUID
        db: Database session
        current_user: Current authenticated user
        
    Returns:
        Machine details
    """
    machine = db.query(Machine).filter(Machine.id == machine_id).first()
    
    if not machine:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Machine not found"
        )

    # Calculate collections dynamically
    # Online: UPI + Card (success)
    online_total = db.query(func.sum(Payment.amount))\
        .filter(
            Payment.machine_id == machine_id,
            Payment.status == 'success',
            Payment.method.in_(['UPI', 'Card'])
        ).scalar() or 0.0

    # Offline: Cash (success)
    offline_total = db.query(func.sum(Payment.amount))\
        .filter(
            Payment.machine_id == machine_id,
            Payment.status == 'success',
            Payment.method.in_(['Cash'])
        ).scalar() or 0.0
    
    return {
        "success": True,
        "data": MachineResponse(
            id=str(machine.id),
            user_id=str(machine.user_id),
            name=machine.name,
            location=machine.location,
            username=machine.username,
            status=machine.status,
            upi_id=machine.upi_id,
            location_id=str(machine.location_id) if machine.location_id else None,
            last_sync=machine.last_sync,
            online_collection=float(online_total),
            offline_collection=float(offline_total),
            created_at=machine.created_at,
            updated_at=machine.updated_at
        )
    }


@router.put("/{machine_id}", response_model=SuccessResponse[MachineResponse])
async def update_machine(
    machine_id: str,
    machine_data: MachineUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Update machine details.
    
    All fields are optional. Only provided fields will be updated.
    If password is provided, it will be hashed before storing.
    
    Args:
        machine_id: Machine UUID
        machine_data: Updated machine data
        db: Database session
        current_user: Current authenticated user
        
    Returns:
        Updated machine details
    """
    machine = db.query(Machine).filter(
        Machine.id == machine_id,
        Machine.user_id == current_user.id
    ).first()

    if not machine:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Machine not found"
        )

    # Update fields if provided
    if machine_data.name is not None:
        machine.name = machine_data.name
    
    if machine_data.location is not None:
        machine.location = machine_data.location
    
    if machine_data.username is not None:
        # Check if username is already taken by another machine
        existing = db.query(Machine).filter(
            Machine.username == machine_data.username,
            Machine.id != machine_id
        ).first()
        
        if existing:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Username already exists"
            )
        
        machine.username = machine_data.username
    
    if machine_data.password is not None:
        machine.hashed_password = get_password_hash(machine_data.password)

    if machine_data.upi_id is not None:
        machine.upi_id = machine_data.upi_id.strip() or None

    if machine_data.location_id is not None:
        machine.location_id = machine_data.location_id or None

    new_status = machine_data.status
    if new_status is not None:
        machine.status = new_status

    try:
        db.commit()
        db.refresh(machine)
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to update machine: {str(e)}"
        )

    # Handle alerts based on new status
    if new_status == 'offline':
        create_alert_if_not_exists(
            db, str(machine.id), AlertSeverity.CRITICAL,
            "Machine Offline", "Machine was manually set to offline"
        )
    elif new_status == 'maintenance':
        create_alert_if_not_exists(
            db, str(machine.id), AlertSeverity.WARNING,
            "Maintenance Mode", "Machine is in maintenance mode"
        )
    elif new_status == 'online':
        resolve_machine_alerts(db, str(machine.id))

    return {
        "success": True,
        "data": MachineResponse(
            id=str(machine.id),
            user_id=str(machine.user_id),
            name=machine.name,
            location=machine.location,
            username=machine.username,
            status=machine.status,
            upi_id=machine.upi_id,
            location_id=str(machine.location_id) if machine.location_id else None,
            last_sync=machine.last_sync,
            online_collection=float(machine.online_collection),
            offline_collection=float(machine.offline_collection),
            created_at=machine.created_at,
            updated_at=machine.updated_at
        )
    }


@router.patch("/{machine_id}/status", response_model=SuccessResponse[MachineResponse])
async def update_machine_status(
    machine_id: str,
    status_data: MachineStatusUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Update machine status, last_sync, and collection amounts.
    
    This endpoint is used by client apps to update their status
    and sync information without requiring all machine fields.
    
    Args:
        machine_id: Machine UUID
        status_data: Status update data
        db: Database session
        current_user: Current authenticated user (or machine)
        
    Returns:
        Updated machine details
    """
    machine = db.query(Machine).filter(
        Machine.id == machine_id,
        Machine.user_id == current_user.id  # Verify ownership
    ).first()
    
    if not machine:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Machine not found"
        )
    
    # Update fields if provided
    if status_data.status is not None:
        machine.status = status_data.status
    
    if status_data.last_sync is not None:
        machine.last_sync = status_data.last_sync
    
    if status_data.online_collection is not None:
        machine.online_collection = status_data.online_collection
    
    if status_data.offline_collection is not None:
        machine.offline_collection = status_data.offline_collection
    
    try:
        db.commit()
        db.refresh(machine)
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to update machine status: {str(e)}"
        )
    
    return {
        "success": True,
        "data": MachineResponse(
            id=str(machine.id),
            user_id=str(machine.user_id),
            name=machine.name,
            location=machine.location,
            username=machine.username,
            status=machine.status,
            upi_id=machine.upi_id,
            location_id=str(machine.location_id) if machine.location_id else None,
            last_sync=machine.last_sync,
            online_collection=float(machine.online_collection),
            offline_collection=float(machine.offline_collection),
            created_at=machine.created_at,
            updated_at=machine.updated_at
        )
    }


@router.delete("/{machine_id}", response_model=MessageResponse)
async def delete_machine(
    machine_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Delete a machine.
    
    Args:
        machine_id: Machine UUID
        db: Database session
        current_user: Current authenticated user
        
    Returns:
        Success message
    """
    machine = db.query(Machine).filter(
        Machine.id == machine_id,
        Machine.user_id == current_user.id  # Verify ownership
    ).first()
    
    if not machine:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Machine not found"
        )
    
    try:
        db.delete(machine)
        db.commit()
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to delete machine: {str(e)}"
        )
    
    return {
        "success": True,
        "message": "Machine deleted successfully"
    }

# ─── Excel / CSV bulk import for service catalog ───────────────────────────

# Keywords used to auto-detect which row is the real column header row
_NAME_KEYWORDS = {"activity", "name", "service", "description", "item", "detail"}
_PRICE_KEYWORDS = {"rate", "price", "amount", "head", "person", "cost", "charge", "tariff"}


def _is_header_row(row_values: list) -> bool:
    """Return True if this row looks like a header (contains name+price keywords)."""
    text = " ".join(str(v).lower() for v in row_values if v is not None)
    has_name = any(kw in text for kw in _NAME_KEYWORDS)
    has_price = any(kw in text for kw in _PRICE_KEYWORDS)
    return has_name and has_price


def _find_col_indices(headers: list[str]):
    """
    Given a list of header strings (already lowercased+stripped),
    return (name_idx, price_idx) or (None, None) if not found.
    """
    name_patterns = [
        "activity name/details", "activity name", "activity", "name",
        "service name", "service", "description", "item", "detail"
    ]
    price_patterns = [
        "rate per head/person", "rate per head", "rate/person", "rate per person",
        "rate", "price", "amount", "charge", "cost", "tariff"
    ]

    name_idx = None
    price_idx = None

    for pat in name_patterns:
        for i, h in enumerate(headers):
            if pat in h:
                name_idx = i
                break
        if name_idx is not None:
            break

    for pat in price_patterns:
        for i, h in enumerate(headers):
            if pat in h and i != name_idx:
                price_idx = i
                break
        if price_idx is not None:
            break

    return name_idx, price_idx


def _clean_price(val) -> Optional[float]:
    """Parse a cell value into a float, stripping currency symbols."""
    if val is None:
        return None
    try:
        return float(str(val).replace("₹", "").replace("Rs", "").replace(",", "").replace(" ", "").strip())
    except (ValueError, TypeError):
        return None


def _parse_excel_bytes(content: bytes) -> tuple[list[dict], str]:
    """
    Parse an xlsx file. Returns (rows_as_dicts, debug_info).
    Auto-detects the real header row (skipping title/subtitle rows at the top).
    """
    try:
        import openpyxl
    except ImportError:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="openpyxl is not installed on the server"
        )

    wb = openpyxl.load_workbook(io.BytesIO(content), data_only=True)
    ws = wb.active
    all_rows = [list(row) for row in ws.iter_rows(values_only=True)]

    if not all_rows:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Excel file is empty.")

    # Find the header row (scan first 10 rows)
    header_row_idx = None
    for i, row in enumerate(all_rows[:10]):
        if _is_header_row(row):
            header_row_idx = i
            break

    if header_row_idx is None:
        # Fallback: treat row 0 as header
        header_row_idx = 0

    raw_headers = all_rows[header_row_idx]
    headers_lower = [str(h).strip().lower() if h is not None else "" for h in raw_headers]
    headers_orig = [str(h).strip() if h is not None else "" for h in raw_headers]

    name_idx, price_idx = _find_col_indices(headers_lower)

    debug = (
        f"Header row detected at index {header_row_idx}. "
        f"Headers: {headers_orig}. "
        f"Name col: {name_idx} ({headers_orig[name_idx] if name_idx is not None else 'NOT FOUND'}), "
        f"Price col: {price_idx} ({headers_orig[price_idx] if price_idx is not None else 'NOT FOUND'})."
    )

    # Positional fallback: if header detection fails, use col index 1 (name) and 2 (price)
    if name_idx is None:
        name_idx = 1
    if price_idx is None:
        price_idx = 2

    data_rows = all_rows[header_row_idx + 1:]
    result = []
    for row in data_rows:
        # Skip entirely empty rows
        if all(v is None or str(v).strip() == "" for v in row):
            continue
        name_val = row[name_idx] if name_idx < len(row) else None
        price_val = row[price_idx] if price_idx < len(row) else None
        result.append({"_name": name_val, "_price": price_val})

    return result, debug


def _parse_csv_bytes(content: bytes) -> tuple[list[dict], str]:
    """Parse a CSV file. Returns (rows_as_dicts, debug_info)."""
    text = content.decode("utf-8-sig")
    lines = [l for l in text.splitlines() if l.strip()]

    # Find the header row
    header_row_idx = 0
    for i, line in enumerate(lines[:10]):
        parts = [p.strip() for p in line.split(",")]
        if _is_header_row(parts):
            header_row_idx = i
            break

    reader = csv.DictReader(io.StringIO("\n".join(lines[header_row_idx:])))
    all_rows = list(reader)
    fieldnames = reader.fieldnames or []
    headers_lower = [h.lower().strip() for h in fieldnames]

    name_idx, price_idx = _find_col_indices(headers_lower)
    name_col = fieldnames[name_idx] if name_idx is not None else (fieldnames[1] if len(fieldnames) > 1 else None)
    price_col = fieldnames[price_idx] if price_idx is not None else (fieldnames[2] if len(fieldnames) > 2 else None)

    debug = f"CSV header row {header_row_idx}. Name col: '{name_col}', Price col: '{price_col}'."
    result = []
    for row in all_rows:
        name_val = row.get(name_col) if name_col else None
        price_val = row.get(price_col) if price_col else None
        if name_val or price_val:
            result.append({"_name": name_val, "_price": price_val})

    return result, debug


@router.post("/{machine_id}/services/bulk-import")
async def bulk_import_services(
    machine_id: str,
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Bulk import services from an Excel (.xlsx) or CSV (.csv) tariff sheet.
    Auto-detects header row and column positions.
    """
    machine = db.query(Machine).filter(Machine.id == machine_id).first()
    if not machine:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Machine not found")

    content = await file.read()
    filename = (file.filename or "").lower()

    try:
        if filename.endswith(".csv"):
            rows, debug_info = _parse_csv_bytes(content)
        elif filename.endswith(".xlsx") or filename.endswith(".xls"):
            rows, debug_info = _parse_excel_bytes(content)
        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Unsupported file type. Please upload a .xlsx or .csv file."
            )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Failed to parse file: {e}")

    if not rows:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The file contains no data rows after the header."
        )

    created, skipped = [], []
    for i, row in enumerate(rows, start=2):
        raw_name = row.get("_name")
        raw_price = row.get("_price")

        name = str(raw_name).strip() if raw_name is not None else None
        # Skip rows where the "name" cell is a number (e.g., Sl. No column bleed)
        if not name or name.replace(".", "").replace(",", "").isdigit():
            skipped.append({"row": i, "reason": f"Missing or invalid name (got: {raw_name!r})"})
            continue

        price = _clean_price(raw_price)
        if price is None or price <= 0:
            skipped.append({"row": i, "reason": f"Invalid price for '{name}' (got: {raw_price!r})"})
            continue

        db.add(Service(machine_id=machine_id, name=name, price=price, status="active"))
        created.append(name)

    if not created:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"No valid services found in the uploaded file. "
                f"Parser debug: {debug_info} — "
                f"Make sure the file has readable 'Activity name/details' and 'Rate Per Head/Person' columns."
            )
        )

    try:
        db.commit()
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Failed to save services: {e}")

    return {
        "success": True,
        "imported": len(created),
        "skipped": len(skipped),
        "skipped_details": skipped,
        "message": f"Successfully imported {len(created)} service(s). {len(skipped)} row(s) skipped."
    }
